name: PR Greeting

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run PR Greeting Bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_GREETING_MESSAGE: "Hello ${username}! Thanks for your PR. We will review it shortly."
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python .github/actions/pr-greeting-bot/greet.py
